services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - order-service
      - payment-service
      - inventory-service
    links:
      - order-service
      - payment-service
      - inventory-service
    environment:
      - REACT_APP_API_URL_INVENTORY=http://inventory-service:8082/inventory
      - REACT_APP_API_URL_ORDER=http://order-service:8080/order
      - REACT_APP_API_URL_PAYMENT=http://payment-service:8081/payment

  order-service:
    build: ./order
    container_name: order-service
    ports:
      - "8080:8080"

  payment-service:
    build: ./payment
    container_name: payment-service
    ports:
      - "8081:8081"

  inventory-service:
    build: ./inventory
    container_name: inventory-service
    ports:
      - "8082:8082"
